# Generated by Django 3.2.4 on 2021-07-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reported_by',
        ),
    ]
