# Generated by Django 3.2.4 on 2021-07-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_organization_deviceapikey_device'),
        ('transaction', '0004_alter_giftcard_gift_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
