# Generated by Django 3.2.4 on 2021-07-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_rename_user_id_card_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_card_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_card_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='transaction.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='transaction.card'),
        ),
    ]
