# Generated by Django 3.2.4 on 2021-07-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20210708_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'managed': True, 'verbose_name': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True, 'verbose_name': 'Transactions'},
        ),
    ]
