# Generated by Django 3.2.4 on 2021-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'managed': True, 'verbose_name': 'Card'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True, 'verbose_name': 'Transaction'},
        ),
    ]
