# Generated by Django 3.2.4 on 2021-07-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20210708_0830'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_rename_organization_deviceapikey_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deviceapikey',
            options={'managed': True, 'ordering': ('-created',), 'verbose_name': 'Device API key', 'verbose_name_plural': 'Device API keys'},
        ),
        migrations.AddField(
            model_name='device',
            name='card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.card'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='deviceapikey',
            table='devices_api_key',
        ),
    ]
