# Generated by Django 3.2.4 on 2021-07-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20210708_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True, 'verbose_name': 'Devices'},
        ),
        migrations.AlterModelTable(
            name='deviceapikey',
            table='devices_api_keys',
        ),
    ]
