# Generated by Django 3.2.4 on 2021-07-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_giftcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='user',
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.giftcard'),
        ),
    ]
