# Generated by Django 3.2.4 on 2021-07-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210702_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='gift_card_no',
            field=models.CharField(max_length=32),
        ),
    ]
