# Generated by Django 3.2.4 on 2021-07-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20210708_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user_id',
            new_name='user',
        ),
    ]
