# Generated by Django 3.2.4 on 2021-07-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceapikey',
            old_name='organization',
            new_name='device',
        ),
    ]
