# Generated by Django 3.2.4 on 2021-07-08 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0003_auto_20210708_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user_id',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
